"use client";

import { type FormEvent, useEffect, useMemo, useState } from "react";
import { Check, FileUp, LogOut, Plus, ReceiptText, ShieldAlert } from "lucide-react";
import { api, type ApiClaim, type ApiUser } from "@/lib/api";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

const money = (amount: number | string, currency = "INR") => new Intl.NumberFormat("en-IN", { style: "currency", currency, maximumFractionDigits: 2 }).format(Number(amount));
const date = (value: string) => new Intl.DateTimeFormat("en-IN", { dateStyle: "medium" }).format(new Date(value));
const statusTone: Record<string, string> = { PAID: "bg-emerald-100 text-emerald-800", APPROVED: "bg-emerald-100 text-emerald-800", REJECTED: "bg-red-100 text-red-800", RETURNED: "bg-amber-100 text-amber-800", MANAGER_REVIEW: "bg-blue-100 text-blue-800", FINANCE_REVIEW: "bg-violet-100 text-violet-800", DRAFT: "bg-slate-100 text-slate-800" };

function Auth({ onAuthenticated }: { onAuthenticated: (user: ApiUser) => void }) {
  const [mode, setMode] = useState<"login" | "register">("login");
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); setBusy(true); try { onAuthenticated(mode === "login" ? await api.login(email, password) : await api.register(name, email, password)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not sign in."); } finally { setBusy(false); } }
  return <main className="grid min-h-screen place-items-center bg-[#f4f7f8] p-5"><form onSubmit={submit} className="w-full max-w-md rounded-3xl border bg-white p-8 shadow-xl"><div className="mb-7 flex items-center gap-3"><div className="grid size-11 place-items-center rounded-xl bg-[#ff6746] text-white"><ReceiptText /></div><div><h1 className="text-2xl font-bold">Ledgerly</h1><p className="text-sm text-slate-500">Expense operations</p></div></div><h2 className="text-xl font-bold">{mode === "login" ? "Sign in" : "Create account"}</h2><p className="mt-1 text-sm text-slate-500">Use the account created by your administrator.</p>{mode === "register" && <label className="mt-5 grid gap-2 text-sm font-medium">Name<Input required value={name} onChange={(e) => setName(e.target.value)} /></label>}<label className="mt-4 grid gap-2 text-sm font-medium">Email<Input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} /></label><label className="mt-4 grid gap-2 text-sm font-medium">Password<Input required type="password" minLength={mode === "register" ? 12 : 1} value={password} onChange={(e) => setPassword(e.target.value)} /></label>{error && <p className="mt-4 text-sm text-red-600">{error}</p>}<Button disabled={busy} className="mt-6 w-full bg-[#172532] text-white">{busy ? "Please wait…" : mode === "login" ? "Sign in" : "Create account"}</Button><button type="button" onClick={() => { setMode(mode === "login" ? "register" : "login"); setError(""); }} className="mt-4 w-full text-sm font-medium text-[#d95235]">{mode === "login" ? "Need an account? Register" : "Already have an account? Sign in"}</button></form></main>;
}

function SubmitExpense({ done }: { done: () => Promise<void> }) {
  const [open, setOpen] = useState(false); const [merchant, setMerchant] = useState(""); const [purpose, setPurpose] = useState(""); const [amount, setAmount] = useState(""); const [category, setCategory] = useState("Meals"); const [file, setFile] = useState<File | null>(null); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setMessage(""); try { const claim = await api.createClaim({ title: merchant, businessPurpose: purpose, currency: "INR", items: [{ category, merchant, amount: Number(amount), expenseDate: new Date().toISOString().slice(0, 10)] }); if (file) await api.uploadReceipt(claim.items[0].id, file); setMessage("Expense submitted for manager review."); await done(); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Could not submit expense."); } finally { setBusy(false); } }
  if (!open) return <Button onClick={() => setOpen(true)} className="bg-[#ff6746] text-white"><Plus /> New expense</Button>;
  return <form onSubmit={submit} className="mb-7 grid gap-3 rounded-2xl border bg-white p-5 md:grid-cols-2"><Input required placeholder="Merchant" value={merchant} onChange={(e) => setMerchant(e.target.value)} /><Input required placeholder="Business purpose" value={purpose} onChange={(e) => setPurpose(e.target.value)} /><Input required type="number" min="0.01" step="0.01" placeholder="Amount (INR)" value={amount} onChange={(e) => setAmount(e.target.value)} /><select value={category} onChange={(e) => setCategory(e.target.value)} className="rounded-md border px-3"><option>Meals</option><option>Travel</option><option>Lodging</option><option>Supplies</option><option>Other</option></select><label className="flex cursor-pointer items-center gap-2 rounded-md border border-dashed p-3 text-sm text-slate-600 md:col-span-2"><FileUp className="size-4" /><input className="sr-only" type="file" accept="image/jpeg,image/png,application/pdf" onChange={(e) => setFile(e.target.files?.[0] ?? null)} />{file?.name ?? "Optional receipt: JPG, PNG, or PDF"}</label>{message && <p className="text-sm md:col-span-2">{message}</p>}<div className="flex gap-2 md:col-span-2"><Button disabled={busy} className="bg-[#172532] text-white">{busy ? "Submitting…" : "Submit expense"}</Button><Button type="button" variant="outline" onClick={() => setOpen(false)}>Cancel</Button></div></form>;
}

function ClaimActions({ claim, user, reload }: { claim: ApiClaim; user: ApiUser; reload: () => Promise<void> }) {
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function perform(action: "approve" | "reject" | "return" | "clarify" | "override" | "pay") { setBusy(true); setMessage(""); try { if (action === "pay") await api.recordPayment(claim.id, new Date().toISOString().slice(0, 10), `LED-${claim.id.slice(0, 8).toUpperCase()}`, Number(claim.totalAmount)); else if (user.roles.includes("MANAGER")) await api.managerDecision(claim.id, action as "approve" | "reject" | "return" | "clarify"); else await api.financeDecision(claim.id, action as "approve" | "reject" | "return" | "override", action === "override" ? "Finance override after review." : undefined); await reload(); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Action failed."); } finally { setBusy(false); } }
  const manager = user.roles.includes("MANAGER") && claim.status === "MANAGER_REVIEW"; const finance = user.roles.includes("FINANCE") && claim.status === "FINANCE_REVIEW"; const payment = user.roles.includes("FINANCE") && claim.status === "APPROVED";
  if (!manager && !finance && !payment) return null;
  return <div className="mt-3 flex flex-wrap gap-2">{manager || finance ? <><Button disabled={busy} size="sm" onClick={() => void perform("approve")} className="bg-emerald-700 text-white"><Check /> Approve</Button><Button disabled={busy} size="sm" variant="outline" onClick={() => void perform("return")}>Return</Button><Button disabled={busy} size="sm" variant="outline" onClick={() => void perform("reject")}>Reject</Button></> : null}{finance && <Button disabled={busy} size="sm" variant="outline" onClick={() => void perform("override")}>Override AI</Button>}{payment && <Button disabled={busy} size="sm" onClick={() => void perform("pay")} className="bg-[#172532] text-white">Record payment</Button>}{message && <p className="w-full text-sm text-red-600">{message}</p>}</div>;
}

function Claims({ claims, user, reload }: { claims: ApiClaim[]; user: ApiUser; reload: () => Promise<void> }) {
  const visible = useMemo(() => user.roles.includes("EMPLOYEE") && !user.roles.some((role) => role !== "EMPLOYEE") ? claims.filter((claim) => claim.employee.id === user.id) : claims, [claims, user]);
  if (!visible.length) return <div className="rounded-2xl border border-dashed bg-white p-10 text-center text-slate-500">No expense claims are visible yet.</div>;
  return <div className="grid gap-4">{visible.map((claim) => <article key={claim.id} className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-bold">{claim.title}</h3><p className="mt-1 text-sm text-slate-500">{claim.employee.name} · {date(claim.createdAt)} · {claim.businessPurpose}</p></div><div className="text-right"><Badge className={statusTone[claim.status] ?? "bg-slate-100 text-slate-800"}>{claim.status.replaceAll("_", " ")}</Badge><p className="mt-2 font-bold">{money(claim.totalAmount, claim.currency)}</p></div></div><div className="mt-4 flex flex-wrap gap-2 text-sm text-slate-600">{claim.items.map((item) => <span key={item.id} className="rounded-md bg-slate-100 px-2 py-1">{item.merchant ?? item.category} · {money(item.amount, claim.currency)}{item.receipts?.length ? " · receipt analyzed" : ""}</span>)}</div>{claim.aiResults?.map((result, index) => <div key={index} className="mt-3 flex gap-2 rounded-lg bg-amber-50 p-3 text-sm text-amber-950"><ShieldAlert className="size-4 shrink-0" />{result.reason}</div>)}<ClaimActions claim={claim} user={user} reload={reload} /></article>)}</div>;
}

function Workspace({ user, onLogout }: { user: ApiUser; onLogout: () => void }) {
  const [claims, setClaims] = useState<ApiClaim[]>([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  async function reload() { setError(""); try { setClaims(await api.claims()); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not load claims."); } finally { setLoading(false); } }
  useEffect(() => { void reload(); }, []);
  return <main className="min-h-screen bg-[#f4f7f8] text-[#172532]"><header className="border-b bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between p-5"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-[#ff6746] text-white"><ReceiptText /></div><div><h1 className="font-bold">Ledgerly</h1><p className="text-xs text-slate-500">{user.name} · {user.roles.join(", ")}</p></div></div><Button variant="outline" onClick={onLogout}><LogOut /> Sign out</Button></div></header><section className="mx-auto max-w-6xl p-5 md:p-8"><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold tracking-widest text-[#d95235]">EXPENSE WORKSPACE</p><h2 className="mt-2 text-3xl font-bold">Claims and reimbursements</h2><p className="mt-2 text-slate-500">Submit, review, and record reimbursement decisions securely.</p></div>{user.roles.includes("EMPLOYEE") && <SubmitExpense done={reload} />}</div>{error && <p className="mb-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{loading ? <p className="text-slate-500">Loading claims…</p> : <Claims claims={claims} user={user} reload={reload} />}</section></main>;
}

export default function Home() {
  const [user, setUser] = useState<ApiUser | null>(null); const [checking, setChecking] = useState(true);
  useEffect(() => { void api.restoreSession().then(setUser).finally(() => setChecking(false)); }, []);
  if (checking) return <main className="grid min-h-screen place-items-center bg-[#f4f7f8] text-slate-500">Loading Ledgerly…</main>;
  return user ? <Workspace user={user} onLogout={() => void api.logout().finally(() => setUser(null))} /> : <Auth onAuthenticated={setUser} />;
}
